#!/usr/bin/env python3
"""Build data/catalog.js from data/cars.json + data/companies.json (no network)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
cars_doc = json.loads((DATA / "cars.json").read_text())
companies_doc = json.loads((DATA / "companies.json").read_text())
payload = {
    "updatedAt": cars_doc.get("updatedAt") or companies_doc.get("updatedAt"),
    "companies": [
        {"name": c["name"], "slug": c.get("slug")} for c in companies_doc.get("companies") or []
    ],
    "cars": cars_doc.get("cars") or [],
}
(DATA / "catalog.js").write_text(
    "/* auto-generated by scripts/build_catalog_js.py — do not edit */\n"
    f"window.__SUV_CATALOG__ = {json.dumps(payload, ensure_ascii=False)};\n"
)
print(f"catalog.js: {len(payload['cars'])} cars, {len(payload['companies'])} companies")
